import { Router } from "express";
import { createMovieController, deleteMovieController, getMovieController, searchMoviesController, sortMoviesAscendingController, sortMoviesDescendingController, updateMovieController } from "../controller/movies.controller.js";


const movieRoute = Router();

// get movies list
movieRoute.get("/get", getMovieController);

// !!!PLEASE NOTE: id passed in params are automatic _id generated by MongoDB, not ID field

// update movie: use params
movieRoute.put("/update/:id", updateMovieController);

// delete movie: use params
movieRoute.delete("/delete/:id", deleteMovieController)

// create movie: use query 
movieRoute.post("/create", createMovieController)

// search movie
movieRoute.get("/search", searchMoviesController)

movieRoute.get('/sort/ascending', sortMoviesAscendingController);
movieRoute.get('/sort/descending', sortMoviesDescendingController);

export default movieRoute;